version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "go-twilio"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15rfbbimbsp1e"
s3_prefix = "go-twilio"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
